In [1]:
import numpy as np

array

In [3]:
arr = np.array([ 1 , 2 , 3 , 4 ])
arr

array([1, 2, 3, 4])

In [5]:
l = [ [1 , 3, 4] , [1 , 2 , 5 ] , [3 , 8 , 9]]
l

[[1, 3, 4], [1, 2, 5], [3, 8, 9]]

In [6]:
np.array(l)

array([[1, 3, 4],
       [1, 2, 5],
       [3, 8, 9]])

Array Generation function


In [10]:
arr2 = np.arange(1 , 11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.zeros((6 , 6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr = np.ones((6 , 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
np.random.rand(5)

array([0.85962501, 0.51619597, 0.85544615, 0.21501036, 0.03982501])

In [22]:
np.random.randn(5)

array([-0.56891092,  1.11325795, -0.52999651, -1.17100415,  0.20212819])

In [26]:
np.random.randint(10 , 20 , 10 )

array([19, 17, 17, 16, 10, 14, 18, 18, 18, 17], dtype=int32)

Array Attributes

In [28]:
arr = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape

(3, 3)

In [30]:
arr.size

9

In [31]:
arr.dtype

dtype('int64')

Array Methods


In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.min()

np.int64(1)

In [34]:
arr.max()

np.int64(9)

In [35]:
arr.sum()

np.int64(45)

In [36]:
np.sum(arr , axis = 0)

array([12, 15, 18])

In [37]:
arr.mean()

np.float64(5.0)

In [38]:
arr.std()


np.float64(2.581988897471611)

In [39]:
arr.argmax()

np.int64(8)

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.argmin()

np.int64(0)

Reshaping and sizing 


In [47]:
arr = np.arange(1 , 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
arr = arr.reshape(6 , 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])