In [2]:
import numpy as np

ARRAY OPERATIONS

Arithmetic operation

In [11]:
a1 = np.array([1 , 2 , 3 , 4 , 5])
a2 = np.array([6 , 7 , 8 , 9 , 10])

In [12]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [13]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [14]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [15]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [16]:
a2 // a1

array([6, 3, 2, 2, 2])

In [17]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [19]:
l = [10 , 20 , 30 , 40]
arr = np.array(l)

In [21]:
arr + 10

array([20, 30, 40, 50])

Deep and Swallow coppy

In [27]:
a = np.arange(1 , 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
slice

array([10, 20, 30, 40, 50])

In [31]:
a
b = a.copy()


In [32]:
b[1] = 99

In [33]:
b

array([ 1, 99,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operation

In [35]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [36]:
A

array([[1, 2],
       [3, 4]])

In [37]:
B

array([[5, 6],
       [7, 8]])

In [38]:
A @ B

array([[19, 22],
       [43, 50]])

In [39]:
A

array([[1, 2],
       [3, 4]])

In [40]:
A.T

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION 
Stacking Array

SyntaxError: invalid syntax (2850362059.py, line 1)

In [45]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [49]:
np.vstack((a , b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
np.hstack((a , b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.column_stack((a , b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [55]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [58]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]