In [4]:
import numpy as np


NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
arr = np.arange(11 , 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[1]

np.int64(12)

In [4]:
arr[1:5:1]

array([12, 13, 14, 15])

NUMPY INDEXING AND SLICING OF MATRIX

In [6]:
arr = np.arange(1,31).reshape(6 , 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [16]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [18]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [7]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

ARRAY OPERATION